// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeAdministracion.Models;

namespace SistemaDeAdministracion.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaDeAdministracion.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaDeIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.ToTable("Alumno");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Hernandez",
                            CarreraId = 1,
                            Dni = "12345679",
                            Domicilio = "",
                            FechaDeIngreso = new DateTime(2019, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaDeNacimiento = new DateTime(1995, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Jose",
                            Sexo = "Masculino"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "sanchez",
                            CarreraId = 1,
                            Dni = "12345679",
                            Domicilio = "av.flores 2458",
                            FechaDeIngreso = new DateTime(2020, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaDeNacimiento = new DateTime(1974, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "carlos",
                            Sexo = "Masculino"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "montes",
                            CarreraId = 3,
                            Dni = "12345679",
                            Domicilio = "calle false 123",
                            FechaDeIngreso = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaDeNacimiento = new DateTime(1984, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "eduardo",
                            Sexo = "Masculino"
                        });
                });

            modelBuilder.Entity("SistemaDeAdministracion.Models.AsignacionDeCursos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Anio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<int>("Semestre")
                        .HasColumnType("int");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("TurnoId");

                    b.ToTable("AsignacionDeCursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = "2021",
                            CursoId = 1,
                            ProfesorId = 1,
                            Semestre = 1,
                            TurnoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Anio = "2021",
                            CursoId = 2,
                            ProfesorId = 2,
                            Semestre = 2,
                            TurnoId = 2
                        },
                        new
                        {
                            Id = 3,
                            Anio = "2021",
                            CursoId = 4,
                            ProfesorId = 3,
                            Semestre = 1,
                            TurnoId = 3
                        });
                });

            modelBuilder.Entity("SistemaDeAdministracion.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carrera");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Ingenieria en sistemas"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "arquitectura"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "analista de sistemas"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "contador"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "abogado"
                        });
                });

            modelBuilder.Entity("SistemaDeAdministracion.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Curso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Matematica"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "ingles"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "fisica"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Programacion"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "comunicacion y redes"
                        });
                });

            modelBuilder.Entity("SistemaDeAdministracion.Models.ItemsAsignacionDeCursos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("AsignacionDeCursosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("AsignacionDeCursosId");

                    b.ToTable("ItemsAsignacionDeCursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlumnoId = 1,
                            AsignacionDeCursosId = 1
                        },
                        new
                        {
                            Id = 2,
                            AlumnoId = 2,
                            AsignacionDeCursosId = 1
                        },
                        new
                        {
                            Id = 3,
                            AlumnoId = 3,
                            AsignacionDeCursosId = 1
                        },
                        new
                        {
                            Id = 4,
                            AlumnoId = 1,
                            AsignacionDeCursosId = 2
                        },
                        new
                        {
                            Id = 5,
                            AlumnoId = 2,
                            AsignacionDeCursosId = 2
                        },
                        new
                        {
                            Id = 6,
                            AlumnoId = 1,
                            AsignacionDeCursosId = 3
                        });
                });

            modelBuilder.Entity("SistemaDeAdministracion.Models.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profesor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "perez",
                            Dni = "98765432",
                            FechaDeNacimiento = new DateTime(1999, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "juan",
                            Sexo = "Masculino"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "castro",
                            Dni = "5452155",
                            FechaDeNacimiento = new DateTime(1986, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "martin",
                            Sexo = "Masculino"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "romero",
                            Dni = "6584255",
                            FechaDeNacimiento = new DateTime(1972, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "juanmanuel",
                            Sexo = "Masculino"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "benitez",
                            Dni = "58766512",
                            FechaDeNacimiento = new DateTime(1990, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "manuel",
                            Sexo = "Masculino"
                        });
                });

            modelBuilder.Entity("SistemaDeAdministracion.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Turno");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "mañana"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "tarde"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "noche"
                        });
                });

            modelBuilder.Entity("SistemaDeAdministracion.Models.Alumno", b =>
                {
                    b.HasOne("SistemaDeAdministracion.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("SistemaDeAdministracion.Models.AsignacionDeCursos", b =>
                {
                    b.HasOne("SistemaDeAdministracion.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeAdministracion.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeAdministracion.Models.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Profesor");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("SistemaDeAdministracion.Models.ItemsAsignacionDeCursos", b =>
                {
                    b.HasOne("SistemaDeAdministracion.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeAdministracion.Models.AsignacionDeCursos", "AsignacionDeCursos")
                        .WithMany("ItemsAsignacionDeCursos")
                        .HasForeignKey("AsignacionDeCursosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("AsignacionDeCursos");
                });

            modelBuilder.Entity("SistemaDeAdministracion.Models.AsignacionDeCursos", b =>
                {
                    b.Navigation("ItemsAsignacionDeCursos");
                });
#pragma warning restore 612, 618
        }
    }
}
